# -*- coding: utf-8 -*-
"""Traffic_Management_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fyq8ZsiyedPVCnKTAam3nP9muBGz_nj6

# Smart Traffic Multi-Agent Ecosystem
This notebook demonstrates a multi-agent system using LangGraph and Google Gemini to monitor traffic, manage incidents, and process penalties.
"""

!pip install -qU langchain-google-genai langgraph pandas

"""## 1. Configuration & Setup
Initializing environment variables, LLM models, and core datasets.
"""

import os
from google.colab import userdata
from langchain_google_genai import ChatGoogleGenerativeAI
from typing import TypedDict, Annotated, List, Dict
import pandas as pd
import json

# Setup LLMs
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY_2')

# Observer: Fast and efficient for unstructured data
llm_observer = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

# Penalty: Higher reasoning for data matching and logic
llm_penalty = ChatGoogleGenerativeAI(model="gemini-2.5-pro")

# Mock Vehicle Dataset
vehicle_data = pd.DataFrame([
    {"plate": "ABC-123", "owner": "John Doe", "email": "john@example.com"},
    {"plate": "XYZ-789", "owner": "Jane Smith", "email": "jane@example.com"}
])

# Expanded Mock Dataset to include registration and owner details for more vehicles
vehicle_data = pd.concat([vehicle_data, pd.DataFrame([
    {"plate": "PARK-999", "owner": "Bob Wilson", "email": "bob@example.com"},
    {"plate": "KID-555", "owner": "Sarah Connor", "email": "sarah@example.com"},
    {"plate": "BUS-111", "owner": "City Transit", "email": "transit@city.gov"}
])], ignore_index=True)

# Mock image data simulation
MOCK_IMAGES = {
    "IMG_001": "[Image: Silver Sedan in No Parking Zone]",
    "IMG_002": "[Image: Blue SUV with 9 passengers visible]",
    "IMG_003": "[Image: Young child behind steering wheel]"
}

"""## 2. Core Agent Nodes
Defining the logic for individual agents: Observers, Penalty Processors, and Managers.
"""

from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated, List, Dict

# 1. Universal State
class TrafficSystemState(TypedDict):
    unstructured_input: str  # For text reports
    raw_sensor_data: Dict     # For patrol vehicle camera/sensor feeds
    refined_data: Dict        # Shared structured data
    penalty_status: str
    notifications_sent: List[str]
    management_action: str
    on_ground_image_ref: str

# 2. Consolidated Agent Nodes

def input_processor_node(state: TrafficSystemState):
    """Initial entry point: Processes either unstructured text or sensor descriptions."""
    # Determine source
    input_text = state.get("unstructured_input") or state.get("raw_sensor_data", {}).get("description", "")
    image_id = state.get("raw_sensor_data", {}).get("image_id")

    prompt = f"""Analyze traffic data: '{input_text}'
    Extract JSON with keys: 'plate', 'violation', 'severity', 'confidence'.
    Identify violations like: No Parking, Overcrowding, Minor Driving, or Median Bypassing.
    """
    response = llm_observer.invoke(prompt)
    clean_content = response.content.replace('```json', '').replace('```', '').strip()
    return {"refined_data": json.loads(clean_content), "on_ground_image_ref": image_id}

def management_orchestrator_node(state: TrafficSystemState):
    """Management agent decides on operational actions."""
    violation = state['refined_data'].get('violation')
    severity = state['refined_data'].get('severity', 'Medium')

    # Fixed: Escaped curly braces to avoid f-string format errors
    prompt = f"As a Traffic Manager, suggest one action for {violation} (Severity: {severity}). Return JSON: {{'action': '...'}}"
    response = llm_penalty.invoke(prompt)
    decision = json.loads(response.content.replace('```json', '').replace('```', '').strip())
    return {"management_action": decision['action']}

def penalty_compliance_node(state: TrafficSystemState):
    """Final node: Issues citations and notifies owners."""
    plate = state['refined_data'].get('plate')
    violation = state['refined_data'].get('violation')

    user_info = vehicle_data[vehicle_data['plate'] == plate]
    if not user_info.empty:
        owner, email = user_info.iloc[0]['owner'], user_info.iloc[0]['email']
        msg = f"NOTIFICATION: Dear {owner}, a penalty for {violation} has been issued for vehicle {plate}. Sent to {email}."
        return {"penalty_status": "Issued", "notifications_sent": [msg]}
    return {"penalty_status": "Vehicle Not Found", "notifications_sent": []}

# 3. Single Unified Graph
builder = StateGraph(TrafficSystemState)

builder.add_node("processor", input_processor_node)
builder.add_node("manager", management_orchestrator_node)
builder.add_node("penalty", penalty_compliance_node)

builder.set_entry_point("processor")
builder.add_edge("processor", "manager")
builder.add_edge("manager", "penalty")
builder.add_edge("penalty", END)

traffic_app = builder.compile()

# Unified Simulation: Running both a Text Report and a Sensor Input through the SAME graph

print("--- Scenario 1: On-Ground Patrol Sensor ---")
sensor_data = {
    "raw_sensor_data": {"description": "Vehicle plate PARK-999 is in a No Parking zone.", "image_id": "IMG_001"}
}
res1 = traffic_app.invoke(sensor_data)
print(f"Action: {res1['management_action']} | Status: {res1['penalty_status']}")
if res1['notifications_sent']: print(res1['notifications_sent'][0])

print("\n--- Scenario 2: Unstructured Text Report ---")
text_report = {"unstructured_input": "A blue car with plate XYZ-789 bypassed the median at high speed."}
res2 = traffic_app.invoke(text_report)
print(f"Action: {res2['management_action']} | Status: {res2['penalty_status']}")
if res2['notifications_sent']: print(res2['notifications_sent'][0])

# Simulate a Smart Patrol Vehicle detection using the consolidated traffic_app
sensor_input = {
    "raw_sensor_data": {
        "description": "Observed a vehicle plate PARK-999 parked directly under a 'No Parking' sign at 2nd Street.",
        "image_id": "IMG_001"
    }
}

# Using the unified traffic_app instead of the old ecosystem_app
final_output = traffic_app.invoke(sensor_input)

print("=== ON-GROUND AGENT ECOSYSTEM REPORT ===")
print(f"Sensor Image: {MOCK_IMAGES.get(final_output['on_ground_image_ref'])}")
print(f"Detected: {final_output['refined_data'].get('violation')}")
print(f"Manager Action: {final_output['management_action']}")
print(f"Penalty Status: {final_output['penalty_status']}")
if final_output['notifications_sent']:
    print(f"Notification: {final_output['notifications_sent'][0]}")

# Sophisticated High-Volume Input
sophisticated_report = """
REPORT: At 08:45 AM, heavy congestion was observed at the intersection of 5th and Main.
Under heavy rain conditions, a silver SUV with plate XYZ-789 was seen bypassing the median
to avoid a line of 20 cars. Traffic flow is currently at 15% capacity with high risk of gridlock.
"""

final_result = traffic_app.invoke({"unstructured_input": sophisticated_report})

print("--- AGENT OUTPUTS ---")
print(f"Refined Context: {json.dumps(final_result['refined_data'], indent=2)}")
print(f"\n[Penalty Agent]: Status -> {final_result['penalty_status']}")
print(f"[Management Agent]: Recommended Action -> {final_result['management_action']}")
if final_result['notifications_sent']:
    print(f"[Notification System]: {final_result['notifications_sent'][0]}")
